### PR TITLE
docs: update documents for 0.4.0 

### PR DESCRIPTION
**Pull request by Fine0830**
Update CHNAGES for 0.4.0 and license

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
Are we going to release binary? I remember there is no binary for browser agent. @arugal

**Comment by arugal** [comment]
> I remember there is no binary for browser agent.

Yes, `client-js` does not have binary.

**Comment by wu-sheng** [comment]
> > I remember there is no binary for browser agent.
> 
> Yes, `client-js` does not have binary.

@Fine0830 Please remove the `dist/*` as we only have source release.

**Comment by Fine0830** [comment]
> > > I remember there is no binary for browser agent.
> > 
> > 
> > Yes, `client-js` does not have binary.
> 
> @Fine0830 Please remove the `dist/*` as we only have source release.

Done

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
