### PR TITLE
feat: monitor static resource information

### PR DESCRIPTION
**Pull request by Fine0830**
Add a new query to report static resource information.

`POST http://localhost:12800/browser/perfData/resources`

Input:

```json
{
  "name": "index.js",
  "duration": 600,
  "size": 100000,
  "protocol": "h2",
  "type": "script",
}
```

Screenshot

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
h2 means?

**Comment by Fine0830** [comment]
> h2 means?

it means https.

**Comment by wu-sheng** [comment]
I see. Let's update the document PR later including the explanation of the fields with values.

**Comment by Fine0830** [comment]
Please check.

**Comment by wu-sheng** [comment]
You should add service, version and page information to this as well. Otherwise, the OAP will not know how to deal with this.

**Comment by Fine0830** [comment]
Updated

**Review by wu-sheng — APPROVED** [review]
Please update the API document accordingly.

**Pull request merged**
