### PR TITLE
fix(trace): add `sw8` to header when using `Fetch` with `Request` to query

### PR DESCRIPTION
**Pull request by Fine0830**
Part of https://github.com/apache/skywalking/issues/12367

Screenshot

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by heyanlong** [comment]
You can make it yourself.

**Comment by wu-sheng** [comment]
> @wu-sheng 可以针对这个提交出个tag包吗？ 急用，谢谢~

Why ping me? I am not the release manager of this repository.

**Comment by WHChen-Alex** [comment]
Sorry  for that 😅

**Comment by WHChen-Alex** [comment]
> > @wu-sheng 可以针对这个提交出个tag包吗？ 急用，谢谢~
> 
> Why ping me? I am not the release manager of this repository.

Sorry for that 😅

**Pull request merged**
