### PR TITLE
Support tracing in axios

### PR DESCRIPTION
**Pull request by zouzou6321**
http header data e.g:
sw8: 1-YTMwN2Q4N2EuZDQ1YS43MzUwZDRiY2RlOWM=-MDc0YTlmNTIuZGE1Zi42NWVjNDhhMDAxMjU=-1-ZmllbGQtcmVwb3J0-ZmllbGQtcmVwb3J0-Lw==-L3Jlc291cmNlL2xpc3RBbGxCeVVzZXJJZEFuZFByb2plY3RJZA==

sw8: 1-YTMwN2Q4N2EuZDQ1YS43MzUwZDRiY2RlOWM=-MDc0YTlmNTIuZGE1Zi42NWVjNDhhMDAxMjU=-2-ZmllbGQtcmVwb3J0-ZmllbGQtcmVwb3J0-Lw==-L2NvbW1vbi9xdWVyeS9yZXBvcnQvdGVtcGxhdGUvY29uZmln

sw8: 1-YTMwN2Q4N2EuZDQ1YS43MzUwZDRiY2RlOWM=-MDc0YTlmNTIuZGE1Zi42NWVjNDhhMDAxMjU=-3-ZmllbGQtcmVwb3J0-ZmllbGQtcmVwb3J0-Lw==-L2NvbW1vbi9xdWVyeS9wcm9qZWN0L2NoYW5uZWxz

sw8: 1-YTMwN2Q4N2EuZDQ1YS43MzUwZDRiY2RlOWM=-MDc0YTlmNTIuZGE1Zi42NWVjNDhhMDAxMjU=-4-ZmllbGQtcmVwb3J0-ZmllbGQtcmVwb3J0-Lw==-L2NvbW1vbi9xdWVyeS9wcm9qZWN0L3Byb2R1Y3Rz

trace segment data e.g:
```json
{
    "traceId": "a307d87a.d45a.7350d4bcde9c",
    "serviceInstance": "field-report",
    "spans": [
        {
            "operationName": "Start",
            "startTime": 1608552148340,
            "endTime": 1608552148340,
            "spanType": "Local",
            "parentSpanId": -1,
            "isError": false,
            "spanLayer": "Http",
            "componentId": 2
        },
        {
            "operationName": "/resource/listAllByUserIdAndProjectId",
            "startTime": 1608552148340,
            "tags": [
                {
                    "key": "http.method",
                    "value": "get"
                },
                {
                    "key": "http.params",
                    "value": "{\"moduleId\":\"5f3a3c9319e820009b08dc95\",\"_rnd\":0.21397797656792372}"
                }
            ],
            "endTime": 1608552149421,
            "spanType": "Exit",
            "parentSpanId": 0,
            "isError": false,
            "spanLayer": "Http",
            "componentId": 2,
            "spanId": 1
        },
        {
            "operationName": "/common/query/report/template/config",
            "startTime": 1608552148341,
            "tags": [
                {
                    "key": "http.method",
                    "value": "get"
                },
                {
                    "key": "http.params",
                    "value": "{\"_rnd\":0.3809034497398498}"
                }
            ],
            "endTime": 1608552149345,
            "spanType": "Exit",
            "parentSpanId": 0,
            "isError": false,
            "spanLayer": "Http",
            "componentId": 2,
            "spanId": 2
        },
        {
            "operationName": "/common/query/project/channels",
            "startTime": 1608552148341,
            "tags": [
                {
                    "key": "http.method",
                    "value": "get"
                },
                {
                    "key": "http.params",
                    "value": "{\"_rnd\":0.2956316605760654}"
                }
            ],
            "endTime": 1608552149382,
            "spanType": "Exit",
            "parentSpanId": 0,
            "isError": false,
            "spanLayer": "Http",
            "componentId": 2,
            "spanId": 3
        },
        {
            "operationName": "/common/query/project/products",
            "startTime": 1608552148341,
            "tags": [
                {
                    "key": "http.method",
                    "value": "get"
                },
                {
                    "key": "http.params",
                    "value": "{\"_rnd\":0.5346148772823016}"
                }
            ],
            "endTime": 1608552149441,
            "spanType": "Exit",
            "parentSpanId": 0,
            "isError": false,
            "spanLayer": "Http",
            "componentId": 2,
            "spanId": 4
        },
        {
            "operationName": "http://localhost:8085/#/",
            "startTime": 1608552149421,
            "tags": [
                {
                    "key": "errorMessage",
                    "value": "{\"uniqueId\":\"d2099c3a.ec3e.144b032b3d31\",\"service\":\"field-report\",\"serviceVersion\":\"field-report\",\"pagePath\":\"index.html\",\"category\":\"promise\",\"grade\":\"Error\",\"errorUrl\":\"\",\"message\":\"error category:promise\\r\\n log info:TypeError: Cannot read property 'forEach' of undefined\\r\\n\\n      error url: \\r\\n other error: undefined\\r\\n\",\"collector\":\"https://*****.com\"}"
                }
            ],
            "endTime": 1608552149421,
            "spanType": "Local",
            "parentSpanId": 0,
            "isError": true,
            "spanLayer": "Http",
            "componentId": 2,
            "spanId": 5
        }
    ],
    "service": "field-report",
    "traceSegmentId": "074a9f52.da5f.65ec48a00125"
}
```

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Please always use English on GitHub

**Comment by wu-sheng** [comment]
1. Update all things to English please. 
2. All new files are required Apache 2.0 headers. 
3. Make CI passed.
4. Keep alive is not required, actually.

We need your example data of trace segment and http header data. Please explain that

@Fine0830 I know you are implementing the tracing too. Could you update the progress here?

**Comment by Fine0830** [comment]
> 1. Update all things to English please.
> 2. All new files are required Apache 2.0 headers.
> 3. Make CI passed.
> 4. Keep alive is not required, actually.
> 
> We need your example data of trace segment and http header data. Please explain that
> 
> @Fine0830 I know you are implementing the tracing too. Could you update the progress here?

OK

**Comment by Fine0830** [comment]
First of all, now, different projects use different HTTP request technology, and there are many libraries and tools to implement this technology, such as `Axios`, `Superagent` ....., and tools such as `OpenAPI` ...... If every library or tool implements an interception, it will be more troublesome. All the front-end HTTP request technologies are implemented based on XMLHttpRequest (`Axios`, `Superagent`) and fetch (`OpenAPI`). Therefore, I think it is better to implement interception from the underlying technology. All projects can be covered only by supporting XMLHttpRequest and fetch interception.
Now, I implemented interception and header settings based on `XMLHttpReques`. Next, I will do `fetch` based part.

**Comment by wu-sheng** [comment]
> Now, I implemented interception and header settings based on XMLHttpReques. Next, I will do fetch based part.
WDYT

Make sense to me. Try to isolate the core implementations, such as assembling the headers, and span/segment in an independent libs, which could be shared in different interceptors.

**Comment by zouzou6321** [comment]
> First of all, now, different projects use different HTTP request technology, and there are many libraries and tools to implement this technology, such as `Axios`, `Superagent` ....., and tools such as `OpenAPI` ...... If every library or tool implements an interception, it will be more troublesome. All the front-end HTTP request technologies are implemented based on `XMLHttpRequest` (`Axios`, `Superagent`) and `fetch` (`OpenAPI`). Therefore, I think it is better to implement interception from the underlying technology. All projects can be covered only by supporting `XMLHttpRequest` and `fetch` interception.
> Now, I implemented interception and header settings based on `XMLHttpReques`. Next, I will do `fetch` based part.
> WDYT @wu-sheng @zouzou6321


I'm looking forward to using it.

**Pull request closed without merging**
