### PR TITLE
feat: support typescript project

### PR DESCRIPTION
**Pull request by mage3k**

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
`package-lock.json ` seems to change 192 lines. whether these are all necessary? Whether these compiling dependency or runtime dependency?

**Comment by wu-sheng** [comment]
@Fine0830 I think we haven't released 0.5.0, do you want to consider including this? Your call.

**Comment by mage3k** [comment]
> `package-lock.json ` seems to change 192 lines. whether these are all necessary? Whether these compiling dependency or runtime dependency?

Only added a webpack plugin for concat all `d.ts` files, Its compiling dependency.

**Comment by wu-sheng** [comment]
> Only added a webpack plugin for concat all `d.ts` files, Its compiling dependency.

Is `package-lock.json` change reasonable? It seems a big change set.

**Comment by mage3k** [comment]
> > Only added a webpack plugin for concat all `d.ts` files, Its compiling dependency.
> 
> Is `package-lock.json` change reasonable? It seems a big change set.

this file was generated after `npm install`, because `webpack-concat-files-plugin` depends on these packages.

**Comment by wu-sheng** [comment]
Got it. @Fine0830 Your turn.

**Comment by Fine0830** [comment]
I don't understand what this is for and what the scene is for. Could you give a detailed explanation? I don't think it is good that all source files are copied to  the `lib` folder.

**Comment by mage3k** [comment]
> I don't understand what this is for and what the scene is for. Could you give a detailed explanation? I don't think it is good that all source files are copied to the `lib` folder.
> 

These are typescript type declaration files, generated by tsc, not source file. 
when `skywalking-client-js`  installed in ts project will get some type error, without change the source code, this is all I can do

**Comment by Fine0830** [comment]
Got it. Is `webpack-concat-plugin` component better? `webpack-concat-files-plugin` is downloaded only once a week. Please  take notice the license.

**Comment by wu-sheng** [comment]
`webpack-concat-plugin` is ISC license, which is a catalog A license. We are safe about using it.

**Review by Fine0830 — APPROVED** [review]

**Pull request merged**
